# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

apiVersion: v1
kind: Pod
metadata:
  name: pod-bbdev-sample-app
spec:
  containers:
  - securityContext:
      privileged: false
      capabilities:
        add:
          - IPC_LOCK
          - SYS_NICE
    name: bbdev-sample-app
    image: bbdev-sample-app:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    - name: class
      mountPath: /sys/devices
      readOnly: false
    resources:
      requests:
        #intel.com/intel_fec_lte: '1'
        intel.com/intel_fec_5g: '1'
        hugepages-2Mi: 512Mi
        memory: 512Mi
      limits:
        #intel.com/intel_fec_lte: '1'
        intel.com/intel_fec_5g: '1'
        hugepages-2Mi: 512Mi
        memory: 512Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - hostPath:
      path: "/sys/devices"
    name: class
