# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-y += libnes_api
DIRS-y += libnes_cfgfile
DIRS-y += libnes_daemon
DIRS-y += libnes_lookup
DIRS-y += libnes_queue
DIRS-y += libnes_sq
DIRS-y += libnes_acl
DIRS-y += libnes_api_shared

include $(RTE_SDK)/mk/rte.extsubdir.mk
